<template>
  <div class="fill-height">
    <app-hammer>
      <v-spacer />

      <div class="d-flex">
        <v-tabs
          fixed-tabs
          background-color="transparent"
          class="tabs"
          v-model="tab"
        >
          <!-- <v-tabs-slider class="tab-slider"></v-tabs-slider> -->
          <v-tab class="primary--text">
            <v-icon>mdi-gitlab</v-icon>
          </v-tab>

          <v-tab class="primary--text">
            <v-icon>mdi-book-outline</v-icon>
          </v-tab>

          <v-tab class="primary--text">
            <v-icon>mdi-android-messages</v-icon>
          </v-tab>
        </v-tabs>
      </div>

      <v-spacer />
      <v-btn icon> </v-btn>
    </app-hammer>

    <div class="editor--wrapper">
      <div ref="editor" class="editor"></div>
    </div>
  </div>
</template>

<script>
import AppHammer from "@/components/AppHammer";
import ace from "ace-builds";
import "ace-builds/webpack-resolver";
import "ace-builds/src-noconflict/ext-language_tools";
import "ace-builds/src-noconflict/ext-emmet";
import "ace-builds/src-noconflict/ext-linking";
import "ace-builds/src-noconflict/ext-settings_menu";
import { beautify } from "ace-builds/src-noconflict/ext-beautify";
import codeLens from "ace-builds/src-noconflict/ext-code_lens";
import { readFile } from "@/modules/filesystem";
import { extname } from "@/utils";

const fileExtensions = {
  htm: "html",
  xhtml: "html",
  html_vm: "html",
  html: "html",
  asp: "html",
  jade: "pug",
  pug: "pug",
  md: "markdown",
  markdown: "markdown",
  rst: "markdown",
  blink: "blink",
  css: "css",
  scss: "sass",
  sass: "sass",
  less: "less",
  json: "json",
  tsbuildinfo: "json",
  json5: "json",
  jsonl: "json",
  ndjson: "json",
  jinja: "jinja",
  jinja2: "jinja",
  j2: "jinja",
  "jinja-html": "jinja",
  proto: "proto",
  "sublime-project": "sublime",
  "sublime-workspace": "sublime",
  tw: "twine",
  twee: "twine",
  yaml: "yaml",
  "YAML-tmLanguage": "yaml",
  yml: "yaml",
  xml: "xml",
  plist: "xml",
  xsd: "xml",
  dtd: "xml",
  xsl: "xml",
  xslt: "xml",
  resx: "xml",
  iml: "xml",
  xquery: "xml",
  tmLanguage: "xml",
  manifest: "xml",
  project: "xml",
  png: "image",
  jpeg: "image",
  jpg: "image",
  gif: "image",
  ico: "image",
  tif: "image",
  tiff: "image",
  psd: "image",
  psb: "image",
  ami: "image",
  apx: "image",
  bmp: "image",
  bpg: "image",
  brk: "image",
  cur: "image",
  dds: "image",
  dng: "image",
  exr: "image",
  fpx: "image",
  gbr: "image",
  img: "image",
  jbig2: "image",
  jb2: "image",
  jng: "image",
  jxr: "image",
  pgf: "image",
  pic: "image",
  raw: "image",
  webp: "image",
  eps: "image",
  afphoto: "image",
  ase: "image",
  aseprite: "image",
  clip: "image",
  cpt: "image",
  heif: "image",
  heic: "image",
  kra: "image",
  mdp: "image",
  ora: "image",
  pdn: "image",
  reb: "image",
  sai: "image",
  tga: "image",
  xcf: "image",
  jfif: "image",
  ppm: "image",
  pbm: "image",
  pgm: "image",
  pnm: "image",
  esx: "javascript",
  mjs: "javascript",
  js: "javascript",
  jsx: "react",
  tsx: "react_ts",
  "routing.ts": "routing",
  "routing.tsx": "routing",
  "routing.js": "routing",
  "routing.jsx": "routing",
  "routes.ts": "routing",
  "routes.tsx": "routing",
  "routes.js": "routing",
  "routes.jsx": "routing",
  ini: "settings",
  dlc: "settings",
  dll: "settings",
  config: "settings",
  conf: "settings",
  properties: "settings",
  prop: "settings",
  settings: "settings",
  option: "settings",
  props: "settings",
  toml: "settings",
  prefs: "settings",
  "sln.dotsettings": "settings",
  "sln.dotsettings.user": "settings",
  cfg: "settings",
  "d.ts": "typescript-def",
  marko: "markojs",
  astro: "astro",
  pdf: "pdf",
  xlsx: "table",
  xls: "table",
  csv: "table",
  tsv: "table",
  vscodeignore: "vscode",
  vsixmanifest: "vscode",
  vsix: "vscode",
  "code-workplace": "vscode",
  csproj: "visualstudio",
  ruleset: "visualstudio",
  sln: "visualstudio",
  suo: "visualstudio",
  vb: "visualstudio",
  vbs: "visualstudio",
  vcxitems: "visualstudio",
  "vcxitems.filters": "visualstudio",
  vcxproj: "visualstudio",
  "vcxproj.filters": "visualstudio",
  pdb: "database",
  sql: "database",
  pks: "database",
  pkb: "database",
  accdb: "database",
  mdb: "database",
  sqlite: "database",
  sqlite3: "database",
  pgsql: "database",
  postgres: "database",
  psql: "database",
  db: "database",
  db3: "database",
  kql: "kusto",
  cs: "csharp",
  csx: "csharp",
  qs: "qsharp",
  zip: "zip",
  tar: "zip",
  gz: "zip",
  xz: "zip",
  br: "zip",
  bzip2: "zip",
  gzip: "zip",
  brotli: "zip",
  "7z": "zip",
  rar: "zip",
  tgz: "zip",
  vala: "vala",
  zig: "zig",
  exe: "exe",
  msi: "exe",
  java: "java",
  jar: "java",
  jsp: "java",
  c: "c",
  m: "c",
  i: "c",
  mi: "c",
  h: "h",
  cc: "cpp",
  cpp: "cpp",
  cxx: "cpp",
  "c++": "cpp",
  cp: "cpp",
  mm: "cpp",
  mii: "cpp",
  ii: "cpp",
  hh: "hpp",
  hpp: "hpp",
  hxx: "hpp",
  "h++": "hpp",
  hp: "hpp",
  tcc: "hpp",
  inl: "hpp",
  go: "go",
  py: "python",
  pyc: "python-misc",
  whl: "python-misc",
  url: "url",
  sh: "console",
  ksh: "console",
  csh: "console",
  tcsh: "console",
  zsh: "console",
  bash: "console",
  bat: "console",
  cmd: "console",
  awk: "console",
  fish: "console",
  exp: "console",
  ps1: "powershell",
  psm1: "powershell",
  psd1: "powershell",
  ps1xml: "powershell",
  psc1: "powershell",
  pssc: "powershell",
  gradle: "gradle",
  doc: "word",
  docx: "word",
  rtf: "word",
  cer: "certificate",
  cert: "certificate",
  crt: "certificate",
  pub: "key",
  key: "key",
  pem: "key",
  asc: "key",
  gpg: "key",
  passwd: "key",
  woff: "font",
  woff2: "font",
  ttf: "font",
  eot: "font",
  suit: "font",
  otf: "font",
  bmap: "font",
  fnt: "font",
  odttf: "font",
  ttc: "font",
  font: "font",
  fonts: "font",
  sui: "font",
  ntf: "font",
  mrf: "font",
  lib: "lib",
  bib: "lib",
  rb: "ruby",
  erb: "ruby",
  fs: "fsharp",
  fsx: "fsharp",
  fsi: "fsharp",
  fsproj: "fsharp",
  swift: "swift",
  ino: "arduino",
  dockerignore: "docker",
  dockerfile: "docker",
  tex: "tex",
  sty: "tex",
  dtx: "tex",
  ltx: "tex",
  pptx: "powerpoint",
  ppt: "powerpoint",
  pptm: "powerpoint",
  potx: "powerpoint",
  potm: "powerpoint",
  ppsx: "powerpoint",
  ppsm: "powerpoint",
  pps: "powerpoint",
  ppam: "powerpoint",
  ppa: "powerpoint",
  webm: "video",
  mkv: "video",
  flv: "video",
  vob: "video",
  ogv: "video",
  ogg: "video",
  gifv: "video",
  avi: "video",
  mov: "video",
  qt: "video",
  wmv: "video",
  yuv: "video",
  rm: "video",
  rmvb: "video",
  mp4: "video",
  m4v: "video",
  mpg: "video",
  mp2: "video",
  mpeg: "video",
  mpe: "video",
  mpv: "video",
  m2v: "video",
  vdi: "virtual",
  vbox: "virtual",
  "vbox-prev": "virtual",
  ics: "email",
  mp3: "audio",
  flac: "audio",
  m4a: "audio",
  wma: "audio",
  aiff: "audio",
  wav: "audio",
  coffee: "coffee",
  cson: "coffee",
  iced: "coffee",
  txt: "document",
  graphql: "graphql",
  gql: "graphql",
  rs: "rust",
  raml: "raml",
  xaml: "xaml",
  hs: "haskell",
  kt: "kotlin",
  kts: "kotlin",
  patch: "git",
  lua: "lua",
  clj: "clojure",
  cljs: "clojure",
  cljc: "clojure",
  groovy: "groovy",
  r: "r",
  rmd: "r",
  dart: "dart",
  as: "actionscript",
  mxml: "mxml",
  ahk: "autohotkey",
  swf: "flash",
  swc: "swc",
  cmake: "cmake",
  asm: "assembly",
  a51: "assembly",
  inc: "assembly",
  nasm: "assembly",
  s: "assembly",
  ms: "assembly",
  agc: "assembly",
  ags: "assembly",
  aea: "assembly",
  argus: "assembly",
  mitigus: "assembly",
  binsource: "assembly",
  vue: "vue",
  ml: "ocaml",
  mli: "ocaml",
  cmx: "ocaml",
  "js.map": "javascript-map",
  "mjs.map": "javascript-map",
  "cjs.map": "javascript-map",
  "css.map": "css-map",
  lock: "lock",
  hbs: "handlebars",
  mustache: "handlebars",
  pm: "perl",
  raku: "perl",
  hx: "haxe",
  "spec.ts": "test-ts",
  "e2e-spec.ts": "test-ts",
  "test.ts": "test-ts",
  "ts.snap": "test-ts",
  "spec.tsx": "test-jsx",
  "test.tsx": "test-jsx",
  "tsx.snap": "test-jsx",
  "spec.jsx": "test-jsx",
  "test.jsx": "test-jsx",
  "jsx.snap": "test-jsx",
  "spec.js": "test-js",
  "e2e-spec.js": "test-js",
  "test.js": "test-js",
  "js.snap": "test-js",
  "module.ts": "angular",
  "module.js": "angular",
  "ng-template": "angular",
  "component.ts": "angular-component",
  "component.js": "angular-component",
  "guard.ts": "angular-guard",
  "guard.js": "angular-guard",
  "service.ts": "angular-service",
  "service.js": "angular-service",
  "pipe.ts": "angular-pipe",
  "pipe.js": "angular-pipe",
  "filter.js": "angular-pipe",
  "directive.ts": "angular-directive",
  "directive.js": "angular-directive",
  "resolver.ts": "angular-resolver",
  "resolver.js": "angular-resolver",
  pp: "puppet",
  ex: "elixir",
  exs: "elixir",
  eex: "elixir",
  leex: "elixir",
  ls: "livescript",
  erl: "erlang",
  twig: "twig",
  jl: "julia",
  elm: "elm",
  pure: "purescript",
  purs: "purescript",
  tpl: "smarty",
  styl: "stylus",
  re: "reason",
  rei: "reason",
  cmj: "bucklescript",
  merlin: "merlin",
  v: "verilog",
  vhd: "verilog",
  sv: "verilog",
  svh: "verilog",
  nb: "mathematica",
  wl: "wolframlanguage",
  wls: "wolframlanguage",
  njk: "nunjucks",
  nunjucks: "nunjucks",
  robot: "robot",
  sol: "solidity",
  au3: "autoit",
  haml: "haml",
  yang: "yang",
  mjml: "mjml",
  tf: "terraform",
  "tf.json": "terraform",
  tfvars: "terraform",
  tfstate: "terraform",
  "blade.php": "laravel",
  "inky.php": "laravel",
  applescript: "applescript",
  ipa: "applescript",
  cake: "cake",
  feature: "cucumber",
  nim: "nim",
  nimble: "nim",
  apib: "apiblueprint",
  apiblueprint: "apiblueprint",
  riot: "riot",
  tag: "riot",
  vfl: "vfl",
  kl: "kl",
  pcss: "postcss",
  sss: "postcss",
  todo: "todo",
  cfml: "coldfusion",
  cfc: "coldfusion",
  lucee: "coldfusion",
  cfm: "coldfusion",
  cabal: "cabal",
  nix: "nix",
  slim: "slim",
  http: "http",
  rest: "http",
  rql: "restql",
  restql: "restql",
  kv: "kivy",
  graphcool: "graphcool",
  sbt: "sbt",
  apk: "android",
  smali: "android",
  dex: "android",
  env: "tune",
  "gitlab-ci.yml": "gitlab",
  jenkinsfile: "jenkins",
  jenkins: "jenkins",
  cr: "crystal",
  ecr: "crystal",
  "drone.yml": "drone",
  cu: "cuda",
  cuh: "cuda",
  log: "log",
  def: "dotjs",
  dot: "dotjs",
  jst: "dotjs",
  ejs: "ejs",
  ".wakatime-project": "wakatime",
  pde: "processing",
  "stories.js": "storybook",
  "stories.jsx": "storybook",
  "story.js": "storybook",
  "story.jsx": "storybook",
  "stories.ts": "storybook",
  "stories.tsx": "storybook",
  "story.ts": "storybook",
  "story.tsx": "storybook",
  wpy: "wepy",
  hcl: "hcl",
  san: "san",
  djt: "django",
  red: "red",
  fxp: "foxpro",
  prg: "foxpro",
  pot: "i18n",
  po: "i18n",
  mo: "i18n",
  wat: "webassembly",
  wasm: "webassembly",
  ipynb: "jupyter",
  d: "d",
  mdx: "mdx",
  bal: "ballerina",
  balx: "ballerina",
  rkt: "racket",
  bzl: "bazel",
  bazel: "bazel",
  mint: "mint",
  vm: "velocity",
  fhtml: "velocity",
  vtl: "velocity",
  gd: "godot",
  godot: "godot-assets",
  tres: "godot-assets",
  tscn: "godot-assets",
  "azure-pipelines.yml": "azure-pipelines",
  "azure-pipelines.yaml": "azure-pipelines",
  azcli: "azure",
  vagrantfile: "vagrant",
  prisma: "prisma",
  cshtml: "razor",
  vbhtml: "razor",
  abc: "abc",
  ad: "asciidoc",
  adoc: "asciidoc",
  asciidoc: "asciidoc",
  edge: "edge",
  ss: "scheme",
  scm: "scheme",
  lisp: "lisp",
  lsp: "lisp",
  cl: "lisp",
  fast: "lisp",
  stl: "3d",
  obj: "3d",
  ac: "3d",
  blend: "3d",
  mesh: "3d",
  mqo: "3d",
  pmd: "3d",
  pmx: "3d",
  skp: "3d",
  vac: "3d",
  vdp: "3d",
  vox: "3d",
  svg: "svg",
  svelte: "svelte",
  vimrc: "vim",
  gvimrc: "vim",
  exrc: "vim",
  vim: "vim",
  viminfo: "vim",
  moon: "moonscript",
  prw: "advpl_prw",
  prx: "advpl_prw",
  ptm: "advpl_ptm",
  tlpp: "advpl_tlpp",
  ch: "advpl_include",
  iso: "disc",
  f: "fortran",
  f77: "fortran",
  f90: "fortran",
  f95: "fortran",
  f03: "fortran",
  f08: "fortran",
  tcl: "tcl",
  liquid: "liquid",
  p: "prolog",
  pro: "prolog",
  pl: "prolog",
  coco: "coconut",
  sketch: "sketch",
  pwn: "pawn",
  amx: "pawn",
  "4th": "forth",
  fth: "forth",
  frt: "forth",
  iuml: "uml",
  pu: "uml",
  puml: "uml",
  plantuml: "uml",
  wsd: "uml",
  wrap: "meson",
  dhall: "dhall",
  dhallb: "dhall",
  sml: "sml",
  mlton: "sml",
  mlb: "sml",
  sig: "sml",
  fun: "sml",
  cm: "sml",
  lex: "sml",
  use: "sml",
  grm: "sml",
  opam: "opam",
  imba: "imba",
  drawio: "drawio",
  dio: "drawio",
  pas: "pascal",
  unity: "shaderlab",
  sas: "sas",
  sas7bdat: "sas",
  sashdat: "sas",
  astore: "sas",
  ast: "sas",
  sast: "sas",
  nupkg: "nuget",
  command: "command",
  dsc: "denizenscript",
  "code-search": "search",
  mcfunction: "minecraft",
  res: "rescript",
  resi: "rescript",
  b: "brainfuck",
  bf: "brainfuck",
  bicep: "bicep",
  cob: "cobol",
  cbl: "cobol",
  gr: "grain",
  lol: "lolcode",
  idr: "idris",
  ibc: "idris",
  pipeline: "pipeline",
  rego: "opa",
  windi: "windicss",
  scala: "scala",
  sc: "scala",
  ly: "lilypond",
  pgn: "chess",
  fen: "chess",
  gmi: "gemini",
  gemini: "gemini",
};

let editor;

export default {
  components: {
    AppHammer,
  },
  data() {
    return {
      tab: null,
    };
  },
  methods: {
    beautify() {
      beautify.beautify(editor.session);
    },
    reactiveAce() {
      readFile(this.$store.state.editor.file).then(({ data }) => {
        editor.setValue(data);
        editor.clearSelection();
      });

      const ext = extname(this.$store.state.editor.file);
      editor.session.setMode(`ace/mode/${fileExtensions[ext] || "text"}`);
    },
    async createAce() {
      if (editor) {
        editor.destroy();
      }

      editor = ace.edit(this.$refs.editor);
      editor.getSession().setUseWrapMode(true);
      editor.setTheme("ace/theme/monokai");
      editor.setOptions({
        enableBasicAutocompletion: true,
        // enableSnippets: true,
        enableLiveAutocompletion: true,
        enableLinking: true,
      });
      editor.setOption("enableEmmet", true);
      editor.setOption("enableCodeLens", true);

      this.reactiveAce();

      codeLens.registerCodeLensProvider(editor, {
        provideCodeLenses(session, callback) {
          var p = [
            {
              start: { row: 0 },
              command: {
                id: "clearCodeLenses",
                title: "Clear all code lenses",
                arguments: [],
              },
            },
          ];
          var l = session.getLength();

          for (var row = 2; row < l; row++) {
            var line = session.getLine(row);
            var endColumn = line.length;

            var m = /[{>]\s*$/.exec(line);
            if (!m) continue;

            p.push({
              start: {
                row: row,
                column: m.index,
              },
              command: {
                id: "describeCodeLens",
                title: "Line " + (row + 1),
                arguments: ["line", row],
              },
            });

            if (m.index < 10) continue;
            p.push({
              start: {
                row: row,
                column: m.index,
              },
              end: {
                row: row,
                column: m.index + 1,
              },
              command: {
                id: "describeCodeLens",
                title: "column " + endColumn,
                arguments: ["column", endColumn],
              },
            });

            if (m.index < 30) continue;
            p.push({
              start: {
                row: row,
                column: m.index,
              },
              command: {
                id: "describeCodeLens",
                title: "Third Link",
                arguments: ["3", row],
              },
            });
          }
          callback(p);
        },
      });

      editor.session.mergeUndoDeltas = true;

      var staticWordCompleter = {
        getCompletions: function (editor, session, pos, prefix, callback) {
          var wordList = ["foo", "bar", "baz"];
          callback(null, [
            ...wordList.map(function (word) {
              return {
                caption: word,
                value: word,
                meta: "static",
              };
            }),
            ...session.$mode.$highlightRules.$keywordList.map(function (word) {
              return {
                caption: word,
                value: word,
                meta: "keyword",
              };
            }),
          ]);
        },
      };

      editor.completers = [staticWordCompleter];
    },
  },
  watch: {
    "$store.state.editor.file"() {
      this.reactiveAce();
    },
  },
  async mounted() {
    this.createAce();
  },
};
</script>

<style lang="scss" scoped>
.editor--wrapper {
  position: relative;
  width: 100%;
  height: 100%;

  .editor {
    position: absolute;
    width: 100%;
    height: 100%;
  }
}
</style>
